from typing import Set, Dict, Any

class LogScorer:
    def _get_lines(self, text: str) -> Set[str]:
        """
        Extract non-empty lines from text and strip whitespace.

        Args:
            text: Input text.

        Returns:
            Set of normalized lines.
        """
        return {line.strip() for line in text.splitlines() if line.strip()}

    def calculate_score(self, candidate_text: str, gold_text: str) -> Dict[str, Any]:
        """
        Calculate Precision, Recall, and F1 score based on line matching.

        Args:
            candidate_text: Summary generated by the candidate algorithm.
            gold_text: Gold standard summary.

        Returns:
            Dictionary containing precision, recall, f1, and intersection details.
        """
        candidate_lines = self._get_lines(candidate_text)
        gold_lines = self._get_lines(gold_text)

        intersection = candidate_lines.intersection(gold_lines)
        true_positives = len(intersection)

        # Precision: TP / (TP + FP) = TP / len(candidate)
        precision = true_positives / len(candidate_lines) if candidate_lines else 0.0

        # Recall: TP / (TP + FN) = TP / len(gold)
        recall = true_positives / len(gold_lines) if gold_lines else 0.0

        # F1 Score: 2 * (P * R) / (P + R)
        if precision + recall > 0:
            f1 = 2 * (precision * recall) / (precision + recall)
        else:
            f1 = 0.0

        return {
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "f1": round(f1, 4),
            "matches": true_positives,
            "candidate_count": len(candidate_lines),
            "gold_count": len(gold_lines),
            "matched_lines": list(intersection)
        }
