"""Regression tests for Issue #2269.

``_link_jules_pr_to_issue`` used to read ``pr_data.get("user", {}).get("login", "")``
directly. When the ``user`` key is *present* but ``None`` (a documented production
possibility for both Jules/Claude PR representations and GitHub's own null-user REST
payloads), the ``{}`` default never kicks in and the subsequent ``.get`` raises
``AttributeError``. The broad ``except Exception`` in ``_link_jules_pr_to_issue``
then swallows the crash and returns ``False`` without ever calling
``_resolve_jules_pr_issue_number`` or ``_update_jules_pr_body``, silently dropping
the session-to-Issue link.

These tests cover:
  * REQ-001 - ``get_pr_author_login`` precedence/fallthrough over dict PR metadata.
  * REQ-002/003 (AS-002) - nullable/alternate author representations must not block
    session-based Issue linking, for both Claude and Jules session URLs.
  * REQ-004 (AS-003) - missing evidence must never be converted into a false
    success; nullable/alternate author metadata must not change that outcome.
  * REQ-003/004 (AS-004) - a rejected publish must not be reported as success, and
    a subsequent successful publish must be idempotent on reprocessing.
  * REQ-005 (AS-005) - the special-title exemption keeps working when the author
    metadata is nullable/alternate.
  * REQ-002 - ``jules.google.com/task/<id>`` accepts alphanumeric ``<id>`` values,
    not just digits.
"""

from unittest.mock import MagicMock, patch

import pytest

from auto_coder.cloud_manager import CloudManager
from auto_coder.pr_processor import _link_jules_pr_to_issue
from auto_coder.utils import get_pr_author_login

CLAUDE_BODY = "Implements the feature.\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_test2269claude)_"
JULES_BODY = "Implements the feature.\n\nhttps://jules.google.com/session/test2269jules"
JULES_TASK_BODY = "Implements the feature.\n\nhttps://jules.google.com/task/test2269jules"

CLAUDE_SESSION_ID = "session_test2269claude"
JULES_SESSION_ID = "test2269jules"
JULES_TASK_SESSION_ID = "test2269jules"


class TestGetPrAuthorLoginPrecedence:
    """REQ-001: first nonempty string among author(str) > author['login'] > user['login']."""

    def test_user_login_dict(self):
        assert get_pr_author_login({"user": {"login": "developer"}}) == "developer"

    def test_null_user_falls_back_to_author_string(self):
        assert get_pr_author_login({"user": None, "author": "developer"}) == "developer"

    def test_missing_user_uses_author_dict(self):
        assert get_pr_author_login({"author": {"login": "developer"}}) == "developer"

    def test_null_user_and_author_dict(self):
        assert get_pr_author_login({"user": None, "author": {"login": "developer"}}) == "developer"

    def test_author_dict_with_null_login_falls_back_to_user_login(self):
        assert get_pr_author_login({"author": {"login": None}, "user": {"login": "developer"}}) == "developer"

    def test_author_string_takes_precedence_over_user_login(self):
        assert get_pr_author_login({"author": "author-login", "user": {"login": "user-login"}}) == "author-login"

    def test_author_dict_login_takes_precedence_over_user_login(self):
        assert get_pr_author_login({"author": {"login": "author-login"}, "user": {"login": "user-login"}}) == "author-login"

    def test_both_author_fields_missing_or_null_yields_no_login(self):
        assert get_pr_author_login({}) is None
        assert get_pr_author_login({"author": None, "user": None}) is None

    def test_user_login_none_with_no_usable_author_yields_no_login(self):
        assert get_pr_author_login({"user": {"login": None}}) is None

    def test_non_string_author_and_login_values_are_ignored(self):
        assert get_pr_author_login({"author": 12345, "user": {"login": "developer"}}) == "developer"
        assert get_pr_author_login({"author": {"login": 999}, "user": {"login": "developer"}}) == "developer"

    def test_null_user_dict_access_does_not_raise(self):
        # Direct regression for the previously unguarded pr_data.get("user", {}).get(...)
        # AttributeError when 'user' is a present key with a None value.
        assert get_pr_author_login({"user": None}) is None
        assert get_pr_author_login({"user": None, "author": None}) is None


def _make_pr_data(number, body, **author_fields):
    pr_data = {
        "number": number,
        "title": "Add feature",
        "body": body,
        "head": {"ref": f"feature-{number}"},
    }
    pr_data.update(author_fields)
    return pr_data


AUTHOR_REPRESENTATIONS = [
    pytest.param({"user": {"login": "developer"}}, id="user-login"),
    pytest.param({"user": None, "author": "developer"}, id="user-null-author-string"),
    pytest.param({"author": {"login": "developer"}}, id="no-user-author-dict"),
    pytest.param({"user": None, "author": {"login": "developer"}}, id="user-null-author-dict"),
    pytest.param({"author": {"login": None}, "user": {"login": "developer"}}, id="author-null-login-user-fallback"),
]

BODY_CASES = [
    pytest.param(CLAUDE_BODY, CLAUDE_SESSION_ID, id="claude-session-url"),
    pytest.param(JULES_BODY, JULES_SESSION_ID, id="jules-session-url"),
]


class TestSessionPrLinkingAuthorRepresentations:
    """AS-002: nullable/alternate author inputs at the linking boundary still publish."""

    @pytest.mark.parametrize("body,session_id", BODY_CASES)
    @pytest.mark.parametrize("author_fields", AUTHOR_REPRESENTATIONS)
    @patch("auto_coder.util.gh_cache.get_ghapi_client")
    @patch("auto_coder.util.gh_cache.GitHubClient")
    def test_links_pr_to_recorded_issue_regardless_of_author_representation(
        self,
        mock_gh_client_cls,
        mock_get_ghapi_client,
        author_fields,
        body,
        session_id,
        tmp_path,
    ):
        repo_name = "owner/repo"
        cloud_file = tmp_path / "cloud.csv"
        manager = CloudManager(repo_name, cloud_file_path=cloud_file)
        manager.add_session(9100, session_id, provider="test")

        pr_number = 9200
        pr_data = _make_pr_data(pr_number, body, **author_fields)

        mock_client_instance = MagicMock()
        mock_client_instance.token = "fake-token"
        mock_api = MagicMock()
        mock_get_ghapi_client.return_value = mock_api

        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            result = _link_jules_pr_to_issue(repo_name, pr_data, mock_client_instance)

        assert result is True
        mock_api.pulls.update.assert_called_once()
        call_args, call_kwargs = mock_api.pulls.update.call_args
        assert call_args[:3] == ("owner", "repo", pr_number)
        updated_body = call_kwargs["body"]
        assert "close #9100" in updated_body
        assert "https://github.com/owner/repo/issues/9100" in updated_body
        assert body in updated_body
        # The in-memory body downstream processing sees reflects the confirmed update.
        assert pr_data["body"] == updated_body

        # Reprocessing the already-linked body must not duplicate the reference or
        # issue a second update.
        mock_api.pulls.update.reset_mock()
        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            result_again = _link_jules_pr_to_issue(repo_name, pr_data, mock_client_instance)
        assert result_again is True
        mock_api.pulls.update.assert_not_called()
        assert updated_body.lower().count("close #9100") == 1


class TestSessionPrLinkingAlphanumericJulesTaskUrl:
    """REQ-002: jules.google.com/task/<id> IDs may be letters/digits/_/- (not digits-only).

    ``_extract_session_id_candidates`` Pattern 4 previously matched only
    ``jules\\.google\\.com/task/(\\d+)``, so an alphanumeric task ID (as REQ-002
    explicitly allows) produced no candidate at all: local-DB lookup and comment
    search were never attempted, and linking reported unsuccessful despite a
    unique recorded session-to-Issue mapping.
    """

    @patch("auto_coder.util.gh_cache.get_ghapi_client")
    @patch("auto_coder.util.gh_cache.GitHubClient")
    def test_links_pr_with_alphanumeric_jules_task_url_when_author_unavailable(
        self,
        mock_gh_client_cls,
        mock_get_ghapi_client,
        tmp_path,
    ):
        repo_name = "owner/repo"
        cloud_file = tmp_path / "cloud.csv"
        manager = CloudManager(repo_name, cloud_file_path=cloud_file)
        manager.add_session(9100, JULES_TASK_SESSION_ID, provider="test")

        pr_number = 9201
        pr_data = _make_pr_data(pr_number, JULES_TASK_BODY, user=None)

        mock_client_instance = MagicMock()
        mock_client_instance.token = "fake-token"
        mock_api = MagicMock()
        mock_get_ghapi_client.return_value = mock_api

        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            result = _link_jules_pr_to_issue(repo_name, pr_data, mock_client_instance)

        assert result is True
        mock_api.pulls.update.assert_called_once()
        call_args, call_kwargs = mock_api.pulls.update.call_args
        assert call_args[:3] == ("owner", "repo", pr_number)
        updated_body = call_kwargs["body"]
        assert JULES_TASK_BODY in updated_body
        assert "close #9100" in updated_body
        assert "https://github.com/owner/repo/issues/9100" in updated_body
        assert pr_data["body"] == updated_body


class TestSessionPrLinkingNoFalseSuccess:
    """AS-003: missing evidence must never be converted into a chosen Issue."""

    @pytest.mark.parametrize("author_fields", AUTHOR_REPRESENTATIONS + [pytest.param({}, id="no-author-fields-at-all")])
    @patch("auto_coder.util.gh_cache.get_ghapi_client")
    @patch("auto_coder.util.gh_cache.GitHubClient")
    def test_unresolvable_session_returns_unsuccessful_and_leaves_body_unchanged(
        self,
        mock_gh_client_cls,
        mock_get_ghapi_client,
        author_fields,
        tmp_path,
    ):
        repo_name = "owner/repo"
        cloud_file = tmp_path / "cloud.csv"
        # No recorded session-to-issue mapping at all.
        manager = CloudManager(repo_name, cloud_file_path=cloud_file)

        original_body = CLAUDE_BODY
        pr_data = _make_pr_data(9300, original_body, **author_fields)

        mock_client_instance = MagicMock()
        mock_client_instance.token = "fake-token"
        mock_api = MagicMock()
        mock_get_ghapi_client.return_value = mock_api
        # No Issue-bearing title/branch and no search match: comment search returns nothing.
        mock_client_instance.search_issues.return_value = []

        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            result = _link_jules_pr_to_issue(repo_name, pr_data, mock_client_instance)

        assert result is False
        mock_api.pulls.update.assert_not_called()
        assert pr_data["body"] == original_body

    @patch("auto_coder.util.gh_cache.get_ghapi_client")
    @patch("auto_coder.util.gh_cache.GitHubClient")
    def test_ambiguous_shared_session_does_not_choose_an_issue_by_author_identity(
        self,
        mock_gh_client_cls,
        mock_get_ghapi_client,
        tmp_path,
    ):
        repo_name = "owner/repo"
        cloud_file = tmp_path / "cloud.csv"
        manager = CloudManager(repo_name, cloud_file_path=cloud_file)
        # Two issues recorded against the same session id: ambiguous ownership.
        manager.add_session(101, CLAUDE_SESSION_ID, provider="test")
        manager.add_session(102, CLAUDE_SESSION_ID, provider="test")

        pr_data = _make_pr_data(9301, CLAUDE_BODY, user=None, author={"login": None})

        mock_client_instance = MagicMock()
        mock_client_instance.token = "fake-token"
        mock_api = MagicMock()
        mock_get_ghapi_client.return_value = mock_api
        mock_client_instance.search_issues.return_value = []

        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            result = _link_jules_pr_to_issue(repo_name, pr_data, mock_client_instance)

        assert result is False
        mock_api.pulls.update.assert_not_called()
        assert pr_data["body"] == CLAUDE_BODY

    def test_ordinary_pr_without_session_evidence_is_untouched_when_author_unavailable(self):
        pr_data = {
            "number": 9302,
            "title": "Fix a typo",
            "body": "Just a small fix, no session info here.",
            "user": None,
        }
        mock_client_instance = MagicMock()

        result = _link_jules_pr_to_issue("owner/repo", pr_data, mock_client_instance)

        assert result is True  # not applicable, not an error
        mock_client_instance.search_issues.assert_not_called()


class TestSessionPrLinkingPublicationFailureAndRetry:
    """AS-004: a rejected publish is never a local success; a later success is idempotent."""

    @patch("auto_coder.util.gh_cache.get_ghapi_client")
    @patch("auto_coder.util.gh_cache.GitHubClient")
    def test_rejected_update_returns_unsuccessful_and_keeps_original_body(
        self,
        mock_gh_client_cls,
        mock_get_ghapi_client,
        tmp_path,
    ):
        repo_name = "owner/repo"
        cloud_file = tmp_path / "cloud.csv"
        manager = CloudManager(repo_name, cloud_file_path=cloud_file)
        manager.add_session(9400, CLAUDE_SESSION_ID, provider="test")

        original_body = CLAUDE_BODY
        pr_data = _make_pr_data(9401, original_body, user=None, author={"login": None})

        mock_client_instance = MagicMock()
        mock_client_instance.token = "fake-token"
        mock_api = MagicMock()
        mock_api.pulls.update.side_effect = RuntimeError("GitHub rejected the update")
        mock_get_ghapi_client.return_value = mock_api

        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            result = _link_jules_pr_to_issue(repo_name, pr_data, mock_client_instance)

        assert result is False
        assert pr_data["body"] == original_body

        # A later invocation with a working transport succeeds and publishes the link.
        mock_api.pulls.update.reset_mock()
        mock_api.pulls.update.side_effect = None
        mock_api.pulls.update.return_value = {}
        pr_data_retry = _make_pr_data(9401, original_body, user=None, author={"login": None})
        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            retry_result = _link_jules_pr_to_issue(repo_name, pr_data_retry, mock_client_instance)

        assert retry_result is True
        linked_body = pr_data_retry["body"]
        assert "close #9400" in linked_body
        mock_api.pulls.update.assert_called_once()

        # Reprocessing the successfully linked body performs no further update.
        mock_api.pulls.update.reset_mock()
        pr_data_reprocessed = _make_pr_data(9401, linked_body, user=None, author={"login": None})
        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            final_result = _link_jules_pr_to_issue(repo_name, pr_data_reprocessed, mock_client_instance)
        assert final_result is True
        mock_api.pulls.update.assert_not_called()


class TestSessionPrLinkingSpecialTitleExemption:
    """AS-005: special-task title prefixes stay exempt regardless of author representation."""

    SPECIAL_PREFIXES = ["🛡️ Sentinel: ", "🎨 Palette: ", "⚡ Bolt: "]

    @pytest.mark.parametrize("prefix", SPECIAL_PREFIXES)
    @pytest.mark.parametrize("author_fields", AUTHOR_REPRESENTATIONS)
    @patch("auto_coder.util.gh_cache.get_ghapi_client")
    @patch("auto_coder.util.gh_cache.GitHubClient")
    def test_special_prefix_skips_linking_even_with_nullable_author(
        self,
        mock_gh_client_cls,
        mock_get_ghapi_client,
        author_fields,
        prefix,
        tmp_path,
    ):
        repo_name = "owner/repo"
        cloud_file = tmp_path / "cloud.csv"
        manager = CloudManager(repo_name, cloud_file_path=cloud_file)
        manager.add_session(9500, JULES_SESSION_ID, provider="test")

        pr_data = {
            "number": 9501,
            "title": f"{prefix}Routine maintenance",
            "body": JULES_BODY,
            "head": {"ref": "jules-9501"},
            **author_fields,
        }

        mock_client_instance = MagicMock()
        mock_client_instance.token = "fake-token"
        mock_api = MagicMock()
        mock_get_ghapi_client.return_value = mock_api

        with patch("auto_coder.pr_processor.CloudManager", return_value=manager):
            result = _link_jules_pr_to_issue(repo_name, pr_data, mock_client_instance)

        assert result is True
        mock_api.pulls.update.assert_not_called()
        assert pr_data["body"] == JULES_BODY
