"""Non-interactive OpenCode CLI client with Git/GitHub lifecycle enforcement.

Runs a configured OpenCode provider/model once per invocation via
``opencode run --format json``, transporting the complete rendered prompt
through stdin, extracting only the completed final assistant message from
the JSON event stream, and denying any Git or GitHub lifecycle mutation the
model attempts through its shell/tool access before the effect occurs.
Auto-Coder retains exclusive ownership of staging, commits, branches/HEAD,
merges/rebases, pushes, and GitHub Issue/PR lifecycle operations; see
docs/client-features/opencode-local-backend.md.
"""

from __future__ import annotations

import json
import os
import secrets
import shlex
import shutil
import signal
import stat
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from .exceptions import AutoCoderRetryableBackendError, AutoCoderTimeoutError, AutoCoderUsageLimitError
from .llm_backend_config import get_llm_config
from .llm_client_base import LLMClientBase
from .logger_config import get_logger
from .prompt_loader import render_prompt
from .usage_marker_utils import has_http_429_marker, has_usage_marker_match
from .utils import _COMMAND_EXECUTION_CWD

logger = get_logger(__name__)

# Real, read-only forms of Git subcommands the OpenCode agent is allowed to run
# for inspection. Anything else is denied by the generated wrapper before the
# real `git` executable is ever invoked. Kept in sync conceptually with
# MuseClient's read-only allowlist, but intentionally reimplemented here as a
# preventive (deny-before-effect) boundary rather than an after-the-fact audit,
# per Issue #2124 REQ-007.
_READ_ONLY_GIT_COMMANDS = frozenset(
    {
        "blame",
        "cat-file",
        "describe",
        "diff",
        "diff-tree",
        "for-each-ref",
        "grep",
        "log",
        "ls-files",
        "ls-tree",
        "merge-base",
        "name-rev",
        "rev-list",
        "rev-parse",
        "shortlog",
        "show",
        "show-ref",
        "status",
    }
)

_GIT_WRAPPER_SOURCE = '''#!/usr/bin/env python3
"""Generated by Auto-Coder: denies Git lifecycle mutations before they run (Issue #2124 REQ-007)."""
import os
import subprocess
import sys

REAL_GIT = %(real_git)s
# The protected repository's own Git metadata (Issue #2125 REQ-002). OpenCode's
# internal checkpoint/tracking feature runs `git init`/`config`/`add`/`write-tree`
# (and similar mutating subcommands) against its own private, detached
# `--git-dir` under its data directory; those never touch the protected
# repository and must not be denied. Only invocations that actually resolve to
# one of these two paths go through the subcommand allowlist below.
PROTECTED_GIT_DIRS = %(protected_git_dirs)s

_READ_ONLY_COMMANDS = {
    "blame", "cat-file", "check-ignore", "check-attr", "describe", "diff", "diff-files",
    "diff-index", "diff-tree", "for-each-ref", "grep", "log", "ls-files", "ls-remote",
    "ls-tree", "merge-base", "name-rev", "rev-list", "rev-parse", "shortlog", "show",
    "show-ref", "status", "var",
}


def _read_only_special(name, args):
    if name == "branch":
        mutating = {"-d", "-D", "-m", "-M", "-c", "-C", "--delete", "--move", "--copy",
                     "--edit-description", "--set-upstream-to", "--unset-upstream"}
        if any(a in mutating for a in args):
            return False
        if any(a in {"--list", "-l", "--contains", "--no-contains", "--merged", "--no-merged"} for a in args):
            return True
        return not any(not a.startswith("-") for a in args)
    if name == "symbolic-ref":
        return len([a for a in args if not a.startswith("-")]) <= 1
    if name == "tag":
        return not any(not a.startswith("-") for a in args)
    if name == "config":
        mutating = {"--add", "--replace-all", "--unset", "--unset-all", "--rename-section",
                     "--remove-section", "--edit", "-e"}
        if any(a in mutating for a in args):
            return False
        if any(a in {"--get", "--get-all", "--get-regexp", "--get-urlmatch", "-l", "--list"} for a in args):
            return True
        return len([a for a in args if not a.startswith("-")]) <= 1
    if name == "remote":
        return not args or args[0] in {"-v", "show", "get-url"}
    if name == "worktree":
        return not args or args[0] == "list"
    return False


_GLOBAL_OPTIONS_WITH_SEPARATE_VALUE = {
    "-c", "-C", "--git-dir", "--work-tree", "--namespace", "--super-prefix",
    "--exec-path", "--config-env", "--attr-source",
}


def _split_global_options(argv):
    """Skip global `git` options (and their values) to find the real subcommand."""
    index = 0
    while index < len(argv):
        token = argv[index]
        if not token.startswith("-"):
            return token, argv[index + 1:]
        if token in _GLOBAL_OPTIONS_WITH_SEPARATE_VALUE:
            index += 2
            continue
        index += 1
    return None, []


def _explicit_targets(argv, env):
    """Resolve an explicit `--git-dir`/`--work-tree`/`-C` target without invoking git.

    Returns (explicit_git_dir_or_None, explicit_work_tree_or_None, effective_cwd)
    so a caller can decide whether an invocation could possibly touch the
    protected repository's Git metadata *or* its working tree, even before any
    ambient (cwd-discovered) repository is known.
    """
    cwd = os.getcwd()
    git_dir = env.get("GIT_DIR")
    work_tree = env.get("GIT_WORK_TREE")
    index = 0
    while index < len(argv):
        token = argv[index]
        if token == "-C":
            if index + 1 < len(argv):
                cwd = os.path.normpath(os.path.join(cwd, argv[index + 1]))
            index += 2
            continue
        if token.startswith("-C") and len(token) > 2:
            cwd = os.path.normpath(os.path.join(cwd, token[2:]))
            index += 1
            continue
        if token == "--git-dir":
            if index + 1 < len(argv):
                git_dir = argv[index + 1]
            index += 2
            continue
        if token.startswith("--git-dir="):
            git_dir = token[len("--git-dir="):]
            index += 1
            continue
        if token == "--work-tree":
            if index + 1 < len(argv):
                work_tree = argv[index + 1]
            index += 2
            continue
        if token.startswith("--work-tree="):
            work_tree = token[len("--work-tree="):]
            index += 1
            continue
        if not token.startswith("-"):
            break
        if token in _GLOBAL_OPTIONS_WITH_SEPARATE_VALUE:
            index += 2
            continue
        index += 1

    def _abs(path):
        if path is None:
            return None
        return os.path.normpath(path if os.path.isabs(path) else os.path.join(cwd, path))

    return _abs(git_dir), _abs(work_tree), cwd


def _resolves_to_protected_repo(argv, env):
    """True unless this invocation demonstrably cannot touch the protected repo."""
    explicit_git_dir, explicit_work_tree, cwd = _explicit_targets(argv, env)
    if explicit_work_tree is not None and explicit_work_tree in PROTECTED_GIT_DIRS:
        return True
    if explicit_git_dir is not None:
        return explicit_git_dir in PROTECTED_GIT_DIRS
    # No explicit --git-dir/GIT_DIR: resolution falls back to ambient discovery
    # from `cwd`. Ask the real, unwrapped git (a read-only query) what it
    # would resolve to; fail closed (treat as protected) if that cannot be
    # determined.
    try:
        probe = subprocess.run(
            [REAL_GIT, "rev-parse", "--path-format=absolute", "--git-dir"],
            cwd=cwd, capture_output=True, text=True, env=env, timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired):
        return True
    if probe.returncode != 0:
        return True
    return probe.stdout.strip() in PROTECTED_GIT_DIRS


def main(argv):
    env = os.environ.copy()
    if not _resolves_to_protected_repo(argv, env):
        os.execv(REAL_GIT, [REAL_GIT] + argv)
    name, rest = _split_global_options(argv)
    if name in _READ_ONLY_COMMANDS or (name is not None and _read_only_special(name, rest)):
        os.execv(REAL_GIT, [REAL_GIT] + argv)
    sys.stderr.write(
        "auto-coder: 'git " + " ".join(argv) + "' is reserved to Auto-Coder and was denied "
        "before execution; Auto-Coder owns Git lifecycle mutations (Issue #2124 REQ-007).\\n"
    )
    sys.exit(1)


if __name__ == "__main__":
    main(sys.argv[1:])
'''

_GH_WRAPPER_SOURCE = '''#!/usr/bin/env python3
"""Generated by Auto-Coder: denies all gh invocations (Issue #2124 REQ-007)."""
import sys

sys.stderr.write(
    "auto-coder: the gh CLI is reserved to Auto-Coder and is not available to the "
    "OpenCode agent; Auto-Coder owns GitHub Issue/PR lifecycle operations "
    "(Issue #2124 REQ-007).\\n"
)
sys.exit(1)
'''

_RETRYABLE_TRANSPORT_MARKERS = (
    "econnreset",
    "econnrefused",
    "etimedout",
    "socket hang up",
    "fetch failed",
    "network error",
    "connection reset",
    "connection refused",
    "service unavailable",
    "temporarily unavailable",
    "bad gateway",
    "gateway timeout",
    "502 ",
    "503 ",
    "504 ",
    "overloaded",
)

_FORBIDDEN_NO_VALUE = frozenset(
    {
        "--continue",
        "-c",
        "--fork",
        "--share",
        "--auto",
        "--yolo",
        "--dangerously-skip-permissions",
        "--mini",
        "--interactive",
        "-i",
    }
)
_FORBIDDEN_WITH_VALUE = frozenset(
    {
        "--attach",
        "--username",
        "-u",
        "--password",
        "-p",
        "--port",
        "--command",
        "--file",
        "-f",
        "--session",
        "-s",
    }
)
_AUTOCODER_OWNED_WITH_VALUE = frozenset({"--format", "--dir"})
_MODEL_FLAGS = frozenset({"--model", "-m"})
_VALUE_TAKING_ALLOWED = frozenset({"--variant", "--agent", "--title", "--replay-limit"})

# Tool names OpenCode's non-interactive `run` exposes to the model that count as
# pure repository/evidence inspection (Issue #2125 REQ-003). Every other built-in
# tool name (bash, edit, write, task, webfetch, skill, todowrite) and any
# custom/MCP tool must resolve to denied for a no-edit invocation.
_NOEDIT_INSPECTION_TOOLS = frozenset({"read", "glob", "grep"})
_NOEDIT_FORBIDDEN_TOOL_STATE: Dict[str, bool] = {
    "bash": False,
    "edit": False,
    "write": False,
    "task": False,
    "webfetch": False,
    "skill": False,
    "todowrite": False,
}
_NOEDIT_REQUIRED_TOOL_STATE: Dict[str, bool] = {"read": True, "glob": True, "grep": True}

# Directories excluded from the no-edit working-tree comparison because they are
# disposable caches/metadata rather than repository content Auto-Coder publishes.
_NOEDIT_DISPOSABLE_DIRECTORY_NAMES = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        ".agent-tmp",
        ".mypy_cache",
        ".pytest_cache",
        ".cache",
        "__pycache__",
        "node_modules",
    }
)
_NOEDIT_DISPOSABLE_DIRECTORY_PREFIXES = tuple(f"{name}/" for name in _NOEDIT_DISPOSABLE_DIRECTORY_NAMES)


@dataclass(frozen=True)
class _GitGuardState:
    branch: Optional[str]
    head: str
    staged_patch: bytes
    refs: Tuple[Tuple[str, str], ...]


@dataclass(frozen=True)
class _NoEditWorkspaceFile:
    path: str
    contents: bytes
    is_symlink: bool
    mode: int


@dataclass(frozen=True)
class _NoEditWorkspaceMode:
    path: str
    mode: int


@dataclass(frozen=True)
class _NoEditWorkspaceState:
    """Everything REQ-002 protects beyond the branch/HEAD/refs/index `_GitGuardState` covers."""

    status: bytes
    unstaged_patch: bytes
    untracked_files: Tuple[_NoEditWorkspaceFile, ...]
    ignored_files: Tuple[_NoEditWorkspaceFile, ...]
    tracked_modes: Tuple[_NoEditWorkspaceMode, ...]
    directory_modes: Tuple[_NoEditWorkspaceMode, ...]


class OpenCodeClient(LLMClientBase):
    """Run a configured OpenCode provider/model while Auto-Coder keeps Git/GitHub ownership."""

    def __init__(self, backend_name: Optional[str] = None) -> None:
        super().__init__()
        config = get_llm_config()
        self.config_backend = config.get_backend_config(backend_name or "opencode")
        model_name: str = (self.config_backend and self.config_backend.model) or ""
        if not model_name:
            raise RuntimeError("OpenCode backend requires an explicit 'model' value in the form " "'provider/model' (e.g. model = \"anthropic/claude-sonnet-4-5\") in " "configuration; OpenCode's remembered/default model is never selected implicitly.")
        self._validate_model(model_name)
        self.model_name: str = model_name
        self.options = (self.config_backend and self.config_backend.options) or []
        self.options_for_noedit = (self.config_backend and self.config_backend.options_for_noedit) or []
        self.usage_markers = (self.config_backend and self.config_backend.usage_markers) or []
        self.timeout = (self.config_backend and self.config_backend.timeout) or 7200

        override = os.environ.get("AUTOCODER_OPENCODE_CLI")
        self.command = shlex.split(override) if override else ["opencode"]
        try:
            result = subprocess.run(self.command + ["--version"], capture_output=True, text=True, timeout=60)
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise RuntimeError(f"OpenCode CLI is unavailable: {exc}") from exc
        if result.returncode != 0:
            diagnostics = (result.stderr or result.stdout or "").strip()[:400]
            raise RuntimeError(f"OpenCode CLI is installed but unusable (exit code {result.returncode}): {diagnostics or 'no diagnostic output'}. Run 'opencode --version' and verify your installation.")

    @staticmethod
    def _validate_model(model: str) -> None:
        if not model or "/" not in model or model.startswith("/") or model.endswith("/"):
            raise RuntimeError(f"OpenCode model {model!r} must be an explicit 'provider/model' value")

    @classmethod
    def _execution_cwd(cls) -> Path:
        override = _COMMAND_EXECUTION_CWD.get()
        return Path(override) if override else Path.cwd()

    @staticmethod
    def _git(*args: str, cwd: Path) -> "subprocess.CompletedProcess[bytes]":
        return subprocess.run(["git", *args], cwd=cwd, capture_output=True, check=False)

    @classmethod
    def _is_git_repository(cls, cwd: Path) -> bool:
        return cls._git("rev-parse", "--git-dir", cwd=cwd).returncode == 0

    @classmethod
    def _snapshot_refs(cls, cwd: Path) -> Tuple[Tuple[str, str], ...]:
        result = cls._git("for-each-ref", "--format=%(refname) %(objectname)", cwd=cwd)
        if result.returncode != 0:
            raise RuntimeError("Unable to snapshot Git refs before OpenCode execution")
        refs = []
        for line in result.stdout.splitlines():
            ref_name, _, object_name = os.fsdecode(line).partition(" ")
            if object_name:
                refs.append((ref_name, object_name))
        return tuple(refs)

    @classmethod
    def _snapshot_guard(cls, cwd: Path) -> _GitGuardState:
        head = cls._git("rev-parse", "HEAD", cwd=cwd)
        if head.returncode != 0:
            raise RuntimeError("OpenCode backend requires a Git repository with an existing HEAD")
        branch_result = cls._git("symbolic-ref", "--quiet", "--short", "HEAD", cwd=cwd)
        staged = cls._git("diff", "--cached", "--binary", cwd=cwd)
        return _GitGuardState(
            branch=branch_result.stdout.decode().strip() if branch_result.returncode == 0 else None,
            head=head.stdout.decode().strip(),
            staged_patch=staged.stdout,
            refs=cls._snapshot_refs(cwd),
        )

    def _assert_git_lifecycle_preserved(self, before: _GitGuardState, cwd: Path) -> None:
        """Fail closed if the Git lifecycle/index changed despite the wrapper boundary."""
        after = self._snapshot_guard(cwd)
        lifecycle_changed = (after.branch, after.head) != (before.branch, before.head)
        refs_changed = after.refs != before.refs
        index_changed = after.staged_patch != before.staged_patch
        if not (lifecycle_changed or refs_changed or index_changed):
            return

        restore_error: Optional[str] = None
        if lifecycle_changed or refs_changed:
            if before.branch:
                restored = self._git("checkout", "-f", before.branch, cwd=cwd)
                if restored.returncode != 0:
                    restored = self._git("checkout", "-B", before.branch, before.head, cwd=cwd)
            else:
                restored = self._git("update-ref", "--no-deref", "HEAD", before.head, cwd=cwd)
            if restored.returncode != 0:
                restore_error = "Auto-Coder could not restore the pre-OpenCode branch/HEAD"
            current_refs = dict(self._snapshot_refs(cwd))
            expected_refs = dict(before.refs)
            for ref_name in current_refs.keys() - expected_refs.keys():
                if self._git("update-ref", "-d", ref_name, cwd=cwd).returncode != 0:
                    restore_error = restore_error or f"Auto-Coder could not remove OpenCode-created ref {ref_name}"
            for ref_name, object_name in expected_refs.items():
                if current_refs.get(ref_name) != object_name:
                    if self._git("update-ref", ref_name, object_name, cwd=cwd).returncode != 0:
                        restore_error = restore_error or f"Auto-Coder could not restore OpenCode-modified ref {ref_name}"

        if self._git("reset", "--mixed", before.head, cwd=cwd).returncode != 0:
            restore_error = restore_error or "Auto-Coder could not unstage OpenCode's index changes"
        elif before.staged_patch:
            apply_result = subprocess.run(["git", "apply", "--binary", "--cached"], cwd=cwd, input=before.staged_patch, capture_output=True)
            if apply_result.returncode != 0:
                restore_error = restore_error or "Auto-Coder could not restore the pre-OpenCode index"

        detail = "lifecycle/ref" if (lifecycle_changed or refs_changed) else "index"
        message = f"OpenCode performed a reserved Git {detail} mutation despite the enforced command boundary; the invocation is rejected"
        if restore_error:
            message += f" ({restore_error})"
        logger.error(message)
        raise RuntimeError(message)

    # -- No-edit working-tree preservation (Issue #2125 REQ-002) ---------------

    @classmethod
    def _noedit_scan_files(cls, raw_paths: bytes, cwd: Path) -> Tuple[_NoEditWorkspaceFile, ...]:
        files = []
        for raw_path in filter(None, raw_paths.split(b"\0")):
            relative_path = os.fsdecode(raw_path)
            normalized = relative_path.replace(os.sep, "/")
            if any(normalized.startswith(prefix) or f"/{prefix}" in f"/{normalized}" for prefix in _NOEDIT_DISPOSABLE_DIRECTORY_PREFIXES):
                continue
            path = cwd / relative_path
            if path.is_symlink():
                files.append(_NoEditWorkspaceFile(relative_path, os.fsencode(os.readlink(path)), True, stat.S_IMODE(path.lstat().st_mode)))
            elif path.is_file():
                files.append(_NoEditWorkspaceFile(relative_path, path.read_bytes(), False, stat.S_IMODE(path.stat().st_mode)))
        return tuple(files)

    @classmethod
    def _noedit_scan_modes(cls, raw_paths: bytes, cwd: Path) -> Tuple[_NoEditWorkspaceMode, ...]:
        modes = []
        for raw_path in filter(None, raw_paths.split(b"\0")):
            relative_path = os.fsdecode(raw_path)
            normalized = relative_path.replace(os.sep, "/")
            if any(normalized.startswith(prefix) or f"/{prefix}" in f"/{normalized}" for prefix in _NOEDIT_DISPOSABLE_DIRECTORY_PREFIXES):
                continue
            path = cwd / relative_path
            if path.exists() and not path.is_symlink():
                modes.append(_NoEditWorkspaceMode(relative_path, stat.S_IMODE(path.stat().st_mode)))
        return tuple(modes)

    @classmethod
    def _noedit_scan_directory_modes(cls, cwd: Path) -> Tuple[_NoEditWorkspaceMode, ...]:
        modes = [_NoEditWorkspaceMode(".", stat.S_IMODE(cwd.stat().st_mode))]
        for current_root, directories, _files in os.walk(cwd, followlinks=False):
            directories[:] = sorted(directory for directory in directories if not (Path(current_root) == cwd and directory in _NOEDIT_DISPOSABLE_DIRECTORY_NAMES))
            for directory in directories:
                path = Path(current_root) / directory
                if not path.is_symlink():
                    modes.append(_NoEditWorkspaceMode(str(path.relative_to(cwd)), stat.S_IMODE(path.stat().st_mode)))
        return tuple(modes)

    @classmethod
    def _snapshot_noedit_workspace(cls, cwd: Path) -> _NoEditWorkspaceState:
        status = cls._git("status", "--porcelain=v2", "--untracked-files=all", "--ignored=matching", cwd=cwd)
        if status.returncode != 0:
            raise RuntimeError("Unable to snapshot the working tree before an OpenCode no-edit execution")
        untracked = cls._noedit_scan_files(cls._git("ls-files", "--others", "--exclude-standard", "-z", cwd=cwd).stdout, cwd)
        ignored = cls._noedit_scan_files(cls._git("ls-files", "--others", "--ignored", "--exclude-standard", "-z", cwd=cwd).stdout, cwd)
        tracked_modes = cls._noedit_scan_modes(cls._git("ls-files", "-z", cwd=cwd).stdout, cwd)
        return _NoEditWorkspaceState(
            status=status.stdout,
            unstaged_patch=cls._git("diff", "--binary", cwd=cwd).stdout,
            untracked_files=untracked,
            ignored_files=ignored,
            tracked_modes=tracked_modes,
            directory_modes=cls._noedit_scan_directory_modes(cwd),
        )

    def _restore_noedit_workspace(self, before: _NoEditWorkspaceState, cwd: Path) -> None:
        clean_args = ["clean", "-fdx"]
        for name in sorted(_NOEDIT_DISPOSABLE_DIRECTORY_NAMES):
            clean_args.extend(["-e", f"{name}/", "-e", name])
        if self._git("checkout", "--", ".", cwd=cwd).returncode != 0 or self._git(*clean_args, cwd=cwd).returncode != 0:
            raise RuntimeError("Auto-Coder could not restore the pre-OpenCode working tree")
        if before.unstaged_patch:
            apply_result = subprocess.run(["git", "apply", "--binary"], cwd=cwd, input=before.unstaged_patch, capture_output=True)
            if apply_result.returncode != 0:
                raise RuntimeError("Auto-Coder could not restore the pre-OpenCode unstaged patch")
        for workspace_file in before.untracked_files + before.ignored_files:
            path = cwd / workspace_file.path
            path.parent.mkdir(parents=True, exist_ok=True)
            if workspace_file.is_symlink:
                if path.exists() or path.is_symlink():
                    path.unlink()
                path.symlink_to(os.fsdecode(workspace_file.contents))
            else:
                path.write_bytes(workspace_file.contents)
                path.chmod(workspace_file.mode)
        for workspace_mode in before.tracked_modes:
            path = cwd / workspace_mode.path
            if path.exists() and not path.is_symlink():
                path.chmod(workspace_mode.mode)
        for directory_mode in before.directory_modes:
            path = cwd / directory_mode.path
            if not path.exists():
                path.mkdir(parents=True)
        for directory_mode in reversed(before.directory_modes):
            path = cwd / directory_mode.path
            if not path.is_symlink():
                path.chmod(directory_mode.mode)

    def _assert_noedit_workspace_preserved(self, before: _NoEditWorkspaceState, cwd: Path) -> None:
        """Fail closed if the no-edit working tree changed despite the permission boundary."""
        after = self._snapshot_noedit_workspace(cwd)
        changed = after.status != before.status or after.unstaged_patch != before.unstaged_patch or after.untracked_files != before.untracked_files or after.ignored_files != before.ignored_files or after.tracked_modes != before.tracked_modes or after.directory_modes != before.directory_modes
        if not changed:
            return
        restore_error: Optional[str] = None
        try:
            self._restore_noedit_workspace(before, cwd)
        except RuntimeError as exc:
            restore_error = str(exc)
        message = "OpenCode modified the working tree during a no-edit invocation despite the enforced permission boundary; the invocation is rejected"
        if restore_error:
            message += f" ({restore_error})"
        logger.error(message)
        raise RuntimeError(message)

    # -- No-edit permission enforcement (Issue #2125 REQ-003/REQ-004) ----------

    @staticmethod
    def _noedit_agent_name() -> str:
        return f"autocoder-noedit-{secrets.token_hex(16)}"

    @staticmethod
    def _noedit_config_content(agent_name: str) -> str:
        """A self-contained OpenCode config granting exactly read/glob/grep.

        Passed via `OPENCODE_CONFIG_CONTENT`, which merges after global config,
        project config, and `.opencode/` directory config (Issue #2125 Context),
        and the agent name is generated fresh per invocation so no pre-existing
        global/project/agent configuration can already define (and thus weaken)
        an agent with this exact name.
        """
        return json.dumps(
            {
                "agent": {
                    agent_name: {
                        "mode": "primary",
                        "permission": {
                            "*": "deny",
                            "read": "allow",
                            "glob": "allow",
                            "grep": "allow",
                        },
                    }
                }
            }
        )

    def _preflight_noedit_policy(self, *, agent_name: str, cwd: Path, env: Dict[str, str]) -> None:
        """Verify the enforcing no-edit policy is actually in force before task launch.

        Issue #2125 REQ-004: if this cannot be established for the installed
        CLI/environment, the call must fail here rather than fall back to an
        editable execution.
        """
        command = [*self.command, "debug", "agent", agent_name]
        try:
            result = subprocess.run(command, cwd=str(cwd), capture_output=True, text=True, timeout=60, env=env)
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise RuntimeError(f"OpenCode no-edit enforcement could not be verified before task launch: {exc}") from exc
        if result.returncode != 0:
            diagnostics = (result.stderr or result.stdout or "").strip()[:400]
            raise RuntimeError(f"OpenCode no-edit enforcement could not be verified before task launch (exit code {result.returncode}): {diagnostics or 'no diagnostic output'}")
        try:
            resolved = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise RuntimeError(f"OpenCode no-edit enforcement could not be verified before task launch: the resolved agent configuration was not valid JSON ({exc}); the enforcing agent may not have been recognized by this OpenCode CLI") from exc
        if not isinstance(resolved, dict) or resolved.get("name") != agent_name:
            raise RuntimeError("OpenCode no-edit enforcement could not be verified before task launch: the enforcing agent was not recognized by the installed OpenCode CLI")
        tools = resolved.get("tools")
        if not isinstance(tools, dict):
            raise RuntimeError("OpenCode no-edit enforcement could not be verified before task launch: no tool policy was resolved for the enforcing agent")
        for tool_name in _NOEDIT_FORBIDDEN_TOOL_STATE:
            if tools.get(tool_name) is not False:
                raise RuntimeError(f"OpenCode no-edit enforcement is not authoritative for this CLI/environment: tool {tool_name!r} resolved to {tools.get(tool_name)!r} instead of denied; refusing to submit the task")
        for tool_name in _NOEDIT_REQUIRED_TOOL_STATE:
            if tools.get(tool_name) is not True:
                raise RuntimeError(f"OpenCode no-edit enforcement could not permit repository inspection for this CLI/environment: tool {tool_name!r} resolved to {tools.get(tool_name)!r} instead of allowed; refusing to submit the task")

    @classmethod
    def _protected_git_dirs(cls, cwd: Path) -> Tuple[str, ...]:
        """The bound repository/worktree's own Git metadata directories.

        Includes both the (possibly worktree-specific) `--git-dir` and the
        shared `--git-common-dir`, so a linked worktree's shared metadata is
        covered too (Issue #2125 REQ-002).
        """
        dirs = []
        for argument in ("--git-dir", "--git-common-dir"):
            result = cls._git("rev-parse", "--path-format=absolute", argument, cwd=cwd)
            if result.returncode != 0:
                raise RuntimeError("Unable to determine Git metadata to protect for OpenCode's command boundary")
            dirs.append(result.stdout.decode().strip())
        return tuple(dict.fromkeys(dirs))

    @classmethod
    def _build_restricted_bin_dir(cls, base_path: Optional[str], cwd: Path) -> str:
        """Create a directory whose git/gh deny reserved Git/GitHub lifecycle operations."""
        real_git = shutil.which("git", path=base_path)
        if not real_git:
            raise RuntimeError("Auto-Coder could not locate the 'git' executable to build OpenCode's command boundary")
        protected_git_dirs = cls._protected_git_dirs(cwd)
        bin_dir = tempfile.mkdtemp(prefix="auto-coder-opencode-bin-")
        try:
            git_wrapper = Path(bin_dir) / "git"
            git_wrapper.write_text(
                _GIT_WRAPPER_SOURCE % {"real_git": json.dumps(real_git), "protected_git_dirs": json.dumps(protected_git_dirs)},
                encoding="utf-8",
            )
            git_wrapper.chmod(0o700)
            gh_wrapper = Path(bin_dir) / "gh"
            gh_wrapper.write_text(_GH_WRAPPER_SOURCE, encoding="utf-8")
            gh_wrapper.chmod(0o700)
        except BaseException:
            shutil.rmtree(bin_dir, ignore_errors=True)
            raise
        return bin_dir

    @staticmethod
    def _kill_process_group(process: "subprocess.Popen[bytes]") -> None:
        try:
            pgid = os.getpgid(process.pid)
        except ProcessLookupError:
            pgid = None
        if pgid is not None:
            try:
                os.killpg(pgid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        try:
            process.communicate(timeout=15)
        except subprocess.TimeoutExpired as exc:
            raise RuntimeError("OpenCode CLI process group did not terminate after SIGKILL; Auto-Coder cannot confirm the writer stopped and must not promote or start a replacement execution") from exc

    def _inject_provider_credentials(self, env: Dict[str, str]) -> None:
        backend = self.config_backend
        if not backend:
            return
        if backend.api_key and "OPENCODE_API_KEY" not in env:
            env["OPENCODE_API_KEY"] = backend.api_key
        if backend.openai_api_key and "OPENAI_API_KEY" not in env:
            env["OPENAI_API_KEY"] = backend.openai_api_key
        if backend.openai_base_url and "OPENAI_BASE_URL" not in env:
            env["OPENAI_BASE_URL"] = backend.openai_base_url
        if backend.openrouter_api_key and "OPENROUTER_API_KEY" not in env:
            env["OPENROUTER_API_KEY"] = backend.openrouter_api_key
        if backend.openrouter_base_url and "OPENROUTER_BASE_URL" not in env:
            env["OPENROUTER_BASE_URL"] = backend.openrouter_base_url

    @classmethod
    def _partition_options(cls, tokens: List[str], *, allow_model_override: bool, allow_agent_override: bool = True) -> Tuple[List[str], Optional[str]]:
        """Validate options/extra args, rejecting anything that would weaken retained authority.

        Returns the sanitized argv tokens to forward to `opencode run`, plus an
        optional one-time model override extracted from `tokens` (only permitted
        when `allow_model_override` is True, i.e. for per-call extra args).

        `allow_agent_override` is False for a no-edit call: Auto-Coder owns
        `--agent` there to guarantee its generated enforcing agent is what
        actually runs (Issue #2125 REQ-004).
        """
        sanitized: List[str] = []
        model_override: Optional[str] = None
        index = 0
        while index < len(tokens):
            token = tokens[index]
            name, sep, inline_value = token.partition("=")
            has_inline_value = bool(sep)

            if name in _FORBIDDEN_NO_VALUE or name in _FORBIDDEN_WITH_VALUE:
                raise RuntimeError(f"OpenCode option '{name}' is not permitted; Auto-Coder retains authority over this setting")
            if name in _AUTOCODER_OWNED_WITH_VALUE:
                raise RuntimeError(f"OpenCode option '{name}' is not permitted; Auto-Coder owns this setting")
            if name == "--agent" and not allow_agent_override:
                raise RuntimeError("OpenCode option '--agent' is not permitted for a no-edit call; Auto-Coder owns agent selection to enforce the no-edit boundary")
            if name in _MODEL_FLAGS:
                if not allow_model_override:
                    raise RuntimeError("The OpenCode model must be set via the backend's 'model' configuration value, not via 'options'")
                if has_inline_value:
                    model_override = inline_value
                    index += 1
                    continue
                if index + 1 >= len(tokens):
                    raise RuntimeError(f"OpenCode option '{name}' is missing its value")
                model_override = tokens[index + 1]
                index += 2
                continue
            if not name.startswith("-"):
                raise RuntimeError("OpenCode options/extra arguments must not include a positional prompt or file argument; the prompt is transported exclusively via stdin")

            sanitized.append(token)
            if not has_inline_value and name in _VALUE_TAKING_ALLOWED:
                if index + 1 >= len(tokens):
                    raise RuntimeError(f"OpenCode option '{name}' is missing its value")
                sanitized.append(tokens[index + 1])
                index += 2
                continue
            index += 1
        return sanitized, model_override

    @classmethod
    def _looks_retryable(cls, text: str) -> bool:
        lowered = (text or "").lower()
        return any(marker in lowered for marker in _RETRYABLE_TRANSPORT_MARKERS)

    def _extract_final_answer(self, *, stdout: str, stderr: str, returncode: int, is_noedit: bool = False) -> str:
        events: List[Dict[str, Any]] = []
        for line_number, raw_line in enumerate(stdout.splitlines(), start=1):
            line = raw_line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError as exc:
                raise RuntimeError(f"OpenCode emitted a malformed event stream line {line_number}: {exc}") from exc
            if not isinstance(event, dict) or "type" not in event:
                raise RuntimeError(f"OpenCode emitted a malformed event envelope on line {line_number}")
            events.append(event)

        root_session: Optional[str] = None
        had_root_error = False
        error_diagnostics: List[str] = []
        last_step_finish: Optional[Tuple[Optional[str], Optional[str]]] = None
        text_parts: List[Tuple[str, Optional[str], str]] = []

        for event in events:
            session_id = event.get("sessionID")
            if session_id is not None:
                if root_session is None:
                    root_session = session_id
                elif session_id != root_session:
                    raise RuntimeError("OpenCode emitted events for conflicting session identities; rejecting the result")

            event_type = event.get("type")
            if event_type == "error":
                had_root_error = True
                error_diagnostics.append(json.dumps(event.get("error"), ensure_ascii=False, sort_keys=True))
                continue

            if event_type in ("tool_use", "step_start", "step_finish", "text", "reasoning"):
                part = event.get("part")
                if not isinstance(part, dict) or "id" not in part:
                    raise RuntimeError(f"OpenCode emitted a malformed '{event_type}' event without a valid part")
                if event_type == "tool_use" and is_noedit and part.get("tool") not in _NOEDIT_INSPECTION_TOOLS:
                    raise RuntimeError(f"OpenCode attempted the forbidden tool {part.get('tool')!r} during a no-edit invocation; the result is rejected regardless of whether the attempt itself succeeded or was denied (Issue #2125 REQ-003/REQ-006)")
                if event_type == "step_finish":
                    reason = part.get("reason") or part.get("finishReason")
                    message_id = part.get("messageID") or part.get("messageId")
                    last_step_finish = (reason, message_id)
                elif event_type == "text":
                    text = part.get("text")
                    if not isinstance(text, str):
                        raise RuntimeError("OpenCode emitted a text event without text content")
                    message_id = part.get("messageID") or part.get("messageId")
                    text_parts.append((part["id"], message_id, text))

        diagnostic_text = "\n".join(part for part in (stderr, *error_diagnostics) if part).strip()
        combined_output = "\n".join(part for part in (stdout, stderr) if part).strip()
        markers = self.usage_markers or ["rate limit", "usage limit", "quota exceeded", "quota_exceeded"]

        if had_root_error:
            classification_text = diagnostic_text or combined_output
            if has_usage_marker_match(classification_text, markers) or has_http_429_marker(classification_text):
                raise AutoCoderUsageLimitError(classification_text or "OpenCode usage limit reached")
            if self._looks_retryable(classification_text):
                raise AutoCoderRetryableBackendError(classification_text or "OpenCode reported a transient provider transport failure")
            raise RuntimeError(f"OpenCode CLI reported a session error: {classification_text or '(no diagnostic detail)'}")

        if returncode != 0:
            classification_text = diagnostic_text or combined_output
            if has_usage_marker_match(classification_text, markers) or has_http_429_marker(classification_text):
                raise AutoCoderUsageLimitError(classification_text or "OpenCode usage limit reached")
            if self._looks_retryable(classification_text):
                raise AutoCoderRetryableBackendError(classification_text or "OpenCode transport failure")
            raise RuntimeError(f"OpenCode CLI failed with return code {returncode}\n{combined_output}")

        if last_step_finish is None:
            raise RuntimeError("OpenCode did not emit a completed step_finish event; the result is incomplete")

        reason, final_message_id = last_step_finish
        if reason != "stop":
            raise RuntimeError(f"OpenCode did not complete normally (finish reason: {reason!r}); refusing to promote a tool-call-only or truncated result")

        seen_part_ids: Set[str] = set()
        final_texts: List[str] = []
        for part_id, message_id, text in text_parts:
            if message_id != final_message_id or part_id in seen_part_ids:
                continue
            seen_part_ids.add(part_id)
            final_texts.append(text)

        if not final_texts:
            raise RuntimeError("OpenCode completed without producing a final assistant text message")

        return "\n\n".join(text.strip() for text in final_texts if text.strip())

    def _run_llm_cli(self, prompt: str, is_noedit: bool = False) -> str:
        cwd = self._execution_cwd()
        if not self._is_git_repository(cwd):
            raise RuntimeError("OpenCode backend requires an execution directory inside a Git repository")

        raw_extra_args = self.consume_extra_args()
        effective_options = self.options_for_noedit if (is_noedit and self.options_for_noedit) else self.options
        sanitized_options, _unused_override = self._partition_options(effective_options, allow_model_override=False, allow_agent_override=not is_noedit)
        sanitized_extra, model_override = self._partition_options(raw_extra_args, allow_model_override=True, allow_agent_override=not is_noedit)
        effective_model = self.model_name
        if model_override:
            self._validate_model(model_override)
            effective_model = model_override

        env = os.environ.copy()
        self._inject_provider_credentials(env)
        bin_dir = self._build_restricted_bin_dir(env.get("PATH"), cwd)
        env["PATH"] = bin_dir + os.pathsep + (env.get("PATH") or "")

        noedit_agent_name: Optional[str] = None
        if is_noedit:
            noedit_agent_name = self._noedit_agent_name()
            env["OPENCODE_CONFIG_CONTENT"] = self._noedit_config_content(noedit_agent_name)
            self._preflight_noedit_policy(agent_name=noedit_agent_name, cwd=cwd, env=env)

        before = self._snapshot_guard(cwd)
        workspace_before = self._snapshot_noedit_workspace(cwd) if is_noedit else None
        rendered_prompt = render_prompt("opencode.noedit_execution" if is_noedit else "opencode.execution", task_prompt=prompt)

        command = [*self.command, "run", "--format", "json", "--dir", str(cwd), "--model", effective_model, *sanitized_options, *sanitized_extra]
        if noedit_agent_name is not None:
            command += ["--agent", noedit_agent_name]

        try:
            logger.warning("LLM invocation: OpenCode CLI is being called. Keep LLM calls minimized.")
            logger.info(f"Running OpenCode CLI with model {effective_model} in {cwd} (no-edit={is_noedit})")

            process: Optional["subprocess.Popen[bytes]"] = None
            try:
                process = subprocess.Popen(command, cwd=str(cwd), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env, start_new_session=True)
            except OSError as exc:
                raise RuntimeError(f"OpenCode CLI could not be executed: {exc}") from exc

            try:
                stdout_bytes, stderr_bytes = process.communicate(input=rendered_prompt.encode("utf-8"), timeout=self.timeout)
            except subprocess.TimeoutExpired as exc:
                self._kill_process_group(process)
                self._assert_git_lifecycle_preserved(before, cwd)
                if workspace_before is not None:
                    self._assert_noedit_workspace_preserved(workspace_before, cwd)
                raise AutoCoderTimeoutError(f"OpenCode CLI timed out after {self.timeout} seconds") from exc

            self._assert_git_lifecycle_preserved(before, cwd)
            if workspace_before is not None:
                self._assert_noedit_workspace_preserved(workspace_before, cwd)

            stdout = stdout_bytes.decode("utf-8", errors="replace")
            stderr = (stderr_bytes or b"").decode("utf-8", errors="replace").strip()
            return self._extract_final_answer(stdout=stdout, stderr=stderr, returncode=process.returncode, is_noedit=is_noedit)
        finally:
            shutil.rmtree(bin_dir, ignore_errors=True)

    def check_mcp_server_configured(self, server_name: str) -> bool:
        return False

    def add_mcp_server_config(self, server_name: str, command: str, args: list[str]) -> bool:
        return False
